// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd_pmUBw9Fqe7mre8m5ibVQopggr3It5I',
    appId: '1:215035424615:web:7cfe267cd6cefaf88c89c2',
    messagingSenderId: '215035424615',
    projectId: 'influancer-thinkalize',
    authDomain: 'influancer-thinkalize.firebaseapp.com',
    storageBucket: 'influancer-thinkalize.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp5d4E9Ssi-UnB_2z1ahjRJIqC2dynyos',
    appId: '1:215035424615:android:2dc4e274a85686c78c89c2',
    messagingSenderId: '215035424615',
    projectId: 'influancer-thinkalize',
    storageBucket: 'influancer-thinkalize.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW2JxupyPnTxmgTyr7cELX21yRp_nJw3U',
    appId: '1:215035424615:ios:cafe556f7d50a68a8c89c2',
    messagingSenderId: '215035424615',
    projectId: 'influancer-thinkalize',
    storageBucket: 'influancer-thinkalize.appspot.com',
    iosClientId:
        '215035424615-ctdm04h2u0u39coj8sev477hsdm26hor.apps.googleusercontent.com',
    iosBundleId: 'com.azzurri.influencer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW2JxupyPnTxmgTyr7cELX21yRp_nJw3U',
    appId: '1:215035424615:ios:cafe556f7d50a68a8c89c2',
    messagingSenderId: '215035424615',
    projectId: 'influancer-thinkalize',
    storageBucket: 'influancer-thinkalize.appspot.com',
    iosClientId:
        '215035424615-ctdm04h2u0u39coj8sev477hsdm26hor.apps.googleusercontent.com',
    iosBundleId: 'com.azzurri.influencer',
  );
}
